// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruzknsqkkbzyleqmmboc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1emtuc3Fra2J6eWxlcW1tYm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjE4MDMsImV4cCI6MjA3NTEzNzgwM30.3ZD33cDx2epaSAQrmQkwhHBjR31ona1Yt22hEzkhBX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});